# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climbot5d_joint_control.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Climbot5d_joint_control(object):
    def setupUi(self, Climbot5d_joint_control):
        Climbot5d_joint_control.setObjectName("Climbot5d_joint_control")
        Climbot5d_joint_control.resize(434, 403)
        self.pushButton_5 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 250, 60, 50))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 10, 60, 50))
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_4 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 170, 60, 50))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 170, 60, 50))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 60, 50))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_10 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 330, 60, 50))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_7 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 90, 60, 50))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 330, 60, 50))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 90, 60, 50))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_9 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 250, 60, 50))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label.setGeometry(QtCore.QRect(210, 90, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_2.setGeometry(QtCore.QRect(210, 190, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_3.setGeometry(QtCore.QRect(210, 140, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_4.setGeometry(QtCore.QRect(210, 240, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_5.setGeometry(QtCore.QRect(210, 290, 67, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 90, 70, 25))
        self.lineEdit_2.setDragEnabled(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 140, 70, 25))
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 240, 70, 25))
        self.lineEdit_4.setDragEnabled(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 190, 70, 25))
        self.lineEdit_5.setDragEnabled(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 290, 70, 25))
        self.lineEdit_6.setDragEnabled(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_8.setGeometry(QtCore.QRect(380, 290, 30, 17))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_12.setGeometry(QtCore.QRect(380, 90, 30, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_13.setGeometry(QtCore.QRect(380, 140, 30, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_14.setGeometry(QtCore.QRect(380, 190, 30, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_15.setGeometry(QtCore.QRect(380, 240, 30, 17))
        self.label_15.setObjectName("label_15")
        self.lineEdit = QtWidgets.QLineEdit(Climbot5d_joint_control)
        self.lineEdit.setGeometry(QtCore.QRect(300, 10, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_11 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 50, 80, 30))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_6 = QtWidgets.QLabel(Climbot5d_joint_control)
        self.label_6.setGeometry(QtCore.QRect(190, 10, 101, 17))
        self.label_6.setObjectName("label_6")
        self.pushButton_12 = QtWidgets.QPushButton(Climbot5d_joint_control)
        self.pushButton_12.setGeometry(QtCore.QRect(310, 340, 101, 50))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")

        self.retranslateUi(Climbot5d_joint_control)
        self.pushButton_1.clicked['bool'].connect(Climbot5d_joint_control.I1_add_position)
        self.pushButton_2.clicked['bool'].connect(Climbot5d_joint_control.I1_sub_position)
        self.pushButton_3.clicked['bool'].connect(Climbot5d_joint_control.T2_add_position)
        self.pushButton_7.clicked['bool'].connect(Climbot5d_joint_control.T2_sub_position)
        self.pushButton_4.clicked['bool'].connect(Climbot5d_joint_control.T3_add_position)
        self.pushButton_8.clicked['bool'].connect(Climbot5d_joint_control.T3_sub_position)
        self.pushButton_5.clicked['bool'].connect(Climbot5d_joint_control.T4_add_position)
        self.pushButton_9.clicked['bool'].connect(Climbot5d_joint_control.T4_sub_position)
        self.pushButton_6.clicked['bool'].connect(Climbot5d_joint_control.I5_add_position)
        self.pushButton_10.clicked['bool'].connect(Climbot5d_joint_control.I5_sub_position)
        self.pushButton_12.clicked.connect(Climbot5d_joint_control.stop)
        self.pushButton_11.clicked.connect(Climbot5d_joint_control.change_velocity)
        QtCore.QMetaObject.connectSlotsByName(Climbot5d_joint_control)

    def retranslateUi(self, Climbot5d_joint_control):
        _translate = QtCore.QCoreApplication.translate
        Climbot5d_joint_control.setWindowTitle(_translate("Climbot5d_joint_control", "Biped5d joint control"))
        self.pushButton_5.setText(_translate("Climbot5d_joint_control", "T4(+)"))
        self.pushButton_1.setText(_translate("Climbot5d_joint_control", "I1(+)"))
        self.pushButton_4.setText(_translate("Climbot5d_joint_control", "T3(+)"))
        self.pushButton_8.setText(_translate("Climbot5d_joint_control", "T3(-)"))
        self.pushButton_2.setText(_translate("Climbot5d_joint_control", "I1(-)"))
        self.pushButton_10.setText(_translate("Climbot5d_joint_control", "I5(-)"))
        self.pushButton_7.setText(_translate("Climbot5d_joint_control", "T2(-)"))
        self.pushButton_6.setText(_translate("Climbot5d_joint_control", "I5(+)"))
        self.pushButton_3.setText(_translate("Climbot5d_joint_control", "T2(+)"))
        self.pushButton_9.setText(_translate("Climbot5d_joint_control", "T4(-)"))
        self.label.setText(_translate("Climbot5d_joint_control", "Joint1"))
        self.label_2.setText(_translate("Climbot5d_joint_control", "Joint3"))
        self.label_3.setText(_translate("Climbot5d_joint_control", "Joint2"))
        self.label_4.setText(_translate("Climbot5d_joint_control", "Joint4"))
        self.label_5.setText(_translate("Climbot5d_joint_control", "Joint5"))
        self.label_8.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_12.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_13.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_14.setText(_translate("Climbot5d_joint_control", "deg"))
        self.label_15.setText(_translate("Climbot5d_joint_control", "deg"))
        self.pushButton_11.setText(_translate("Climbot5d_joint_control", "set vel"))
        self.label_6.setText(_translate("Climbot5d_joint_control", "Velocity(deg/s)"))
        self.pushButton_12.setText(_translate("Climbot5d_joint_control", "stop"))

